#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

#do not add synaptics_oppo_driver_4291.o
obj-$(CONFIG_SYNAPTICS_OPPO) += synaptics_oppo_driver_3508.o
obj-$(CONFIG_SYNAPTICS_OPPO) += synaptics_oppo_driver_3320.o
obj-$(CONFIG_SYNAPTICS_OPPO) += synaptics_redremote.o
obj-$(CONFIG_SYNAPTICS_OPPO) += synaptics_touch_key_driver_s1302.o 
obj-$(CONFIG_SYNAPTICS_OPPO) += synaptics_touch_key_s1302_redremote.o

#endif