obj-$(CONFIG_OPPO_COMMON_SOFT)	+=  oppo_project/
obj-$(CONFIG_OPPO_DEVICE_IFNO)	+=  oppo_devinfo/

#ifdef VENDOR_EDIT
#//John.Xu@PhoneSw.AudioDriver.OppoDebug.CriticalLog, 2016/02/22, Add for critical_log
obj-y     +=  oppo_criticallog/
#endif /* VENDOR_EDIT */

#ifdef VENDOR_EDIT
#//jie.cheng@swdh.sh, 2016/04/15, Add hypnus helper
obj-y     +=  oppo_hypnus/
#endif /* VENDOR_EDIT */

# ifdef VENDOR_EDIT 
# Ziqing.Guo@PhoneSw.BSP, 2016/07/23, Add for oppo fingerprint compatibility
obj-$(CONFIG_OPPO_FP_COMMON)	+=  oppo_fp_common/
# endif /* VENDOR_EDIT */
#ifdef VENDOR_EDIT
#//zhenwenxian@BSP.Power.Basic, 2017/01/12, Add for NV recovery
obj-$(CONFIG_RECORD_MDMRST)     +=  oppo_mdmrst/
#endif /* VENDOR_EDIT */