#
# Makefile for cpuidle governors.
#

obj-$(CONFIG_CPU_IDLE_GOV_LADDER) += ladder.o
obj-$(CONFIG_CPU_IDLE_GOV_MENU) += menu.o
#ifdef VENDOR_EDIT
#xiaocheng.li@Swdp.shanghai, 2015/11/9, Add new lpm governor
obj-$(CONFIG_CPU_IDLE_GOV_SCORING) += scoring.o
#endif
