#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHPANEL_SYNAPTICS_S3508) += S3508/
obj-$(CONFIG_TOUCHPANEL_SYNAPTICS_S1302) += S1302_virtal_key/
obj-$(CONFIG_TOUCHPANEL_SYNAPTICS) += synaptics_touch_panel_remote.o
obj-$(CONFIG_TOUCHPANEL_SYNAPTICS) += synaptics_common.o

#endif
