#gt915 touchpanel driver


obj-$(CONFIG_GT5688_TOUCHPANEL_DRIVER)	+= gt1x.o
obj-$(CONFIG_GT5688_TOUCHPANEL_DRIVER)	+= gt1x_extents.o
obj-$(CONFIG_GT5688_TOUCHPANEL_DRIVER)	+= gt1x_generic.o
obj-$(CONFIG_GT5688_TOUCHPANEL_DRIVER)	+= circle_point.o
obj-$(CONFIG_GT5688_TOUCHPANEL_DEBUG)	+= gt1x_tools.o
obj-$(CONFIG_GT5688_TOUCHPANEL_UPDATE)	+= gt1x_update.o