#ifdef VENDOR_EDIT
#John.Xu 2016-02-05 add for tfa9890 and ak4375 multi-project baseline
ifneq ($(filter $(OPPO_TARGET_DEVICE),MSM_16017 MSM_16027),)
snd-soc-tfa98xx-objs := tfa98xx.o tfa_dsp.o tfa_container.o tfa9891_init.o tfa9887_init.o tfa9887B_init.o tfa9888_init.o tfa9890_init.o tfa9897_init.o tfa_debug.o
obj-y += snd-soc-tfa98xx.o
endif
#endif /* VENDOR_EDIT */
